project:
  type: book

book:
  title: "BACO Supplementary Material"
  author: "Aizaz A. Chaudhry"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - introduction.qmd
    - part: "Methods"
      chapters:
        - methods.qmd
    - part: "Results"
      chapters:
        - hearingloss.qmd

format:
  html:
    theme: cosmo